# Generated by Django 4.2.30 on 2026-06-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=140, verbose_name='اسم المشروع (عربي)')),
                ('title_en', models.CharField(max_length=140, verbose_name='اسم المشروع (إنجليزي)')),
                ('category', models.CharField(choices=[('restaurant', 'مطاعم'), ('clinic', 'عيادات'), ('store', 'متاجر'), ('cafe', 'كافيهات'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('short_ar', models.CharField(blank=True, max_length=240, verbose_name='وصف مختصر (عربي)')),
                ('short_en', models.CharField(blank=True, max_length=240, verbose_name='وصف مختصر (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='الصورة')),
                ('url', models.URLField(blank=True, verbose_name='رابط الموقع/العمل')),
                ('client_name', models.CharField(blank=True, max_length=120, verbose_name='اسم العميل')),
                ('year', models.CharField(blank=True, max_length=8, verbose_name='السنة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميّز (يظهر بالرئيسية)')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عمل / مشروع',
                'verbose_name_plural': 'الأعمال',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=120, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(max_length=120, verbose_name='العنوان (إنجليزي)')),
                ('short_ar', models.CharField(max_length=240, verbose_name='وصف مختصر (عربي)')),
                ('short_en', models.CharField(max_length=240, verbose_name='وصف مختصر (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف الكامل (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف الكامل (إنجليزي)')),
                ('icon', models.CharField(choices=[('web', 'تصميم مواقع'), ('ads', 'إعلانات ممولة'), ('social', 'سوشيال ميديا'), ('branding', 'هوية بصرية'), ('seo', 'تحسين محركات البحث'), ('content', 'كتابة محتوى'), ('design', 'تصميم جرافيك'), ('analytics', 'تحليلات وتقارير'), ('photo', 'تصوير منتجات'), ('store', 'متاجر إلكترونية')], default='web', max_length=20, verbose_name='الأيقونة')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='المعرّف (slug)')),
                ('is_featured', models.BooleanField(default=True, verbose_name='مميّزة (تظهر بالرئيسية)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+970 59 000 0000', max_length=40, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(default='970590000000', help_text='مثال: 970590000000', max_length=40, verbose_name='واتساب (بصيغة دولية بدون +)')),
                ('email', models.EmailField(default='info@atharmedia.ps', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address_ar', models.CharField(default='غزة، فلسطين', max_length=200, verbose_name='العنوان (عربي)')),
                ('address_en', models.CharField(default='Gaza, Palestine', max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('working_hours_ar', models.CharField(default='السبت - الخميس: 9 ص - 6 م', max_length=120, verbose_name='ساعات العمل (عربي)')),
                ('working_hours_en', models.CharField(default='Sat - Thu: 9 AM - 6 PM', max_length=120, verbose_name='ساعات العمل (إنجليزي)')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='إنستغرام')),
                ('tiktok', models.URLField(blank=True, verbose_name='تيك توك')),
                ('whatsapp_channel', models.URLField(blank=True, verbose_name='قناة واتساب')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('youtube', models.URLField(blank=True, verbose_name='يوتيوب')),
                ('x_twitter', models.URLField(blank=True, verbose_name='X (تويتر)')),
                ('map_embed', models.TextField(blank=True, help_text='ضع رابط src من خريطة جوجل (Embed). اختياري.', verbose_name='رابط تضمين الخريطة (Google Maps src)')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم العميل')),
                ('business_ar', models.CharField(blank=True, max_length=140, verbose_name='النشاط (عربي)')),
                ('business_en', models.CharField(blank=True, max_length=140, verbose_name='النشاط (إنجليزي)')),
                ('content_ar', models.TextField(verbose_name='الرأي (عربي)')),
                ('content_en', models.TextField(blank=True, verbose_name='الرأي (إنجليزي)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='التقييم (1-5)')),
                ('image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='صورة العميل')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'توصية عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم الهاتف')),
                ('business_type', models.CharField(blank=True, max_length=120, verbose_name='نوع النشاط')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.service', verbose_name='الخدمة المطلوبة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
