# Generated by Django 5.2.16 on 2026-08-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='أي مقاس وأي صيغة — تُقصّ تلقائيًا إلى 4:3 وتُحوَّل إلى WebP مضغوط. اتركها فارغة ليظهر الرسم التخطيطي التلقائي. ارفعها من لوحة التحكم على الموقع المنشور، لأن الصور المرفوعة محليًا لا تصل الخادم.', upload_to='projects/', verbose_name='الصورة'),
        ),
    ]
